#!/usr/bin/env bash

declare NAME='mynginx'
declare NGINX_VOL_IMAGE="nginx_vols"
declare NGINX_VOL_NAME="mynignix02"

# use local index.html
__local() {
  docker run --name ${NAME} -p 7676:80 -d -v ~/docker/web/html:/usr/share/nginx/html nginx
}

__kill() {
  docker kill ${NAME}
  docker rm ${NAME}
}

__grab_conf() {
  docker cp ${NAME}:/etc/nginx/conf.d/default.conf default.conf
}

__conf() {
  docker run --name ${NAME} \
    -p 80:80 \
    -v ~/docker/nginx/html:/usr/share/nginx/html \
    -v ~/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf \
    -d \
    nginx
}

__bake() {
  docker build -t "${NAME}" -f Dockerfile.nginx .
  docker run --name "${NAME}01" -p 7676:80 -d "${NAME}"
}


__volumes() {
  docker build -t "${NGINX_VOL_IMAGE}" -f Dockerfile.volumes .
  docker run --name "${NGINX_VOL_NAME}" -P -d "${NGINX_VOL_IMAGE}"
}

__vol_attach() {
  docker run -it --volumes-from "${NGINX_VOL_NAME}" --name "${NGINX_VOL_NAME}-vols" debian /bin/bash
}


#__grab_conf
action="${1:-local}"
case ${action} in
  local) __local ;;
  kill) __kill   ;;
  grab) __grab_conf ;;
  conf) __conf ;;
  bake) __bake ;;
  vol-at*) __vol_attach ;;
  vol*) __volumes ;;

  *)
    echo "Unknown action: ${action}";
    exit 0;
  ;;
esac
